language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm set registry http://122.192.9.52:35227

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t renjning/annotation:latest .
  - docker push renjning/annotation:latest
